spring:
  application:
    name: user
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8076/eureka/
  instance:
    prefer-ip-address: true #使用ip的方式注册自己的服务
feign:
  hystrix:
    enabled: true #默认false